version: '3'
services: 
    backend:
        image: nalad/uptime-backend:prod
        build: backend
        restart: always
        depends_on:
            - database
        ports:
            - 8080:8080
        environment:
            POSTGRES_DB: $POSTGRES_DB
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    database:
        image: postgres:10-alpine
        environment:
            POSTGRES_DB: $POSTGRES_DB
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        volumes:
            - uptime-pgdata:/var/lib/postgresql/data"

    frontend:
        image: nalad/uptime-frontend:prod
        build: frontend
        restart: always
        ports:
            - 80:80

volumes:
    uptime-pgdata:
